### ISSUE TITLE
py2neo module error

### ISSUE THREAD

**Issue by novem33** [stephenc222/example-graphrag-with-neo4j#1]
Have you ever considered replace py2neo module into new one, becaase py2neo is not maintained anymore?

---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
/tmp/ipykernel_3616/297412259.py in <module>
----> 1 answer_1 = query_handler.ask_question(query_1)

/app/notebook/6_agents/example-graphrag-with-neo4j-main/query_handler.py in ask_question(self, query)
     13 
     14     def ask_question(self, query):
---> 15         centrality_data = self.graph_manager.calculate_centrality_measures()
     16         centrality_summary = self.graph_manager.summarize_centrality_measures(
     17             centrality_data)

/app/notebook/6_agents/example-graphrag-with-neo4j-main/graph_manager.py in calculate_centrality_measures(self, graph_name)
    112     # def calculate_centrality_measures(self, graph_name="entityGraph"):
    113     def calculate_centrality_measures(self, graph_name="neo4j"):
--> 114         self.reproject_graph(graph_name)
    115 
    116         check_query = f"CALL gds.graph.exists($graph_name) YIELD exists"

/app/notebook/6_agents/example-graphrag-with-neo4j-main/graph_manager.py in reproject_graph(self, graph_name)
     79     # def reproject_graph(self, graph_name="entityGraph"):
     80     def reproject_graph(self, graph_name="neo4j"):
---> 81         self.drop_existing_projection(graph_name)
     82         self.verify_relationship_weights()
     83 

/app/notebook/6_agents/example-graphrag-with-neo4j-main/graph_manager.py in drop_existing_projection(self, graph_name)
    178     def drop_existing_projection(self, graph_name):
    179         drop_query = f"CALL gds.graph.exists('{graph_name}') YIELD exists"
--> 180         result = self.graph.run(drop_query).evaluate()
    181         if result:
    182             drop_query = f"CALL gds.graph.drop('{graph_name}')"

/usr/local/lib/python3.10/dist-packages/py2neo/database.py in run(self, cypher, parameters, **kwparameters)
    403         :return:
    404         """
--> 405         return self.auto().run(cypher, parameters, **kwparameters)
    406 
    407     def evaluate(self, cypher, parameters=None, **kwparameters):

/usr/local/lib/python3.10/dist-packages/py2neo/database.py in run(self, cypher, parameters, **kwparameters)
    990                                                   graph_name=self.graph.name,
    991                                                   readonly=self.readonly)
--> 992             self._connector.pull(result, -1)
    993             return Cursor(result, hydrant)
    994         finally:

/usr/local/lib/python3.10/dist-packages/py2neo/client/__init__.py in pull(self, result, n)
   1432         cx = self._reacquire(result.transaction)
   1433         try:
-> 1434             cx.pull(result, n=n)
   1435         except (ConnectionUnavailable, ConnectionBroken):
   1436             self.prune(cx.profile)

/usr/local/lib/python3.10/dist-packages/py2neo/client/bolt.py in pull(self, result, n, capacity)
    999                                         "during pull"), error)
   1000         else:
-> 1001             self._audit(self._transaction)
   1002             return response
   1003 

/usr/local/lib/python3.10/dist-packages/py2neo/client/bolt.py in _audit(self, task)
    808             return
    809         try:
--> 810             task.audit()
    811         except Neo4jError:
    812             self.reset(force=True)

/usr/local/lib/python3.10/dist-packages/py2neo/client/bolt.py in audit(self)
   1138     def audit(self):
   1139         for item in self._items:
-> 1140             item.audit()
   1141 
   1142 

/usr/local/lib/python3.10/dist-packages/py2neo/client/bolt.py in audit(self)
   1138     def audit(self):
   1139         for item in self._items:
-> 1140             item.audit()
   1141 
   1142 

/usr/local/lib/python3.10/dist-packages/py2neo/client/bolt.py in audit(self)
   1301         if self._failure:
   1302             self.set_ignored()
-> 1303             raise self._failure
   1304 
   1305     @property

ClientError: [Procedure.ProcedureNotFound] There is no procedure with the name `gds.graph.exists` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

**Comment by stephenc222** [comment]
It seems the issue is related to the Neo4j server not having the necessary Graph Data Science (GDS) plugin installed or properly configured. The error `[Procedure.ProcedureNotFound] There is no procedure with the name gds.graph.exists registered for this database instance` indicates that the Neo4j instance is missing the GDS library, which is essential for running certain graph algorithms, such as centrality measures.

To resolve this, it would be necessary to install the GDS plugin on the Neo4j server. This can be done by checking the Neo4j dashboard or using Neo4j Desktop to verify if the plugin is enabled. If it's missing, installation steps should be followed, either via Neo4j Desktop or by configuring the `neo4j.conf` file for server instances.

Additionally, while this specific issue isn't directly tied to Py2neo, it would be a good idea to refactor away from Py2neo to the official Neo4j driver SDK for Python. Py2neo is no longer actively maintained, and using the native driver would provide better long-term support and reliability.

**Comment by novem33** [comment]
Really thanks for your answer, I'll try update the plugin. It's good to have your sharing programs and I will follow your amazing ideas.

**Comment by stephenc222** [comment]
Replaced EOL `py2neo` with the officially supported `neo4j` Python driver.

See [commit](https://github.com/stephenc222/example-graphrag-with-neo4j/commit/b4e670edc220bbec82c8a6b49586a955c126fbcb).

Thanks for pointing out the issue with `py2neo`.
